[tool.pysen]
version = "0.11"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true
mypy_preset = "strict"
line_length = 121
py_version = "py312"
[[tool.pysen.lint.mypy_targets]]
  paths = ["."]
