name: Linter
on:
  pull_request:
    paths:
      - '*.py'
  push:
    branches:
      - main
    paths:
      - '*.py'

jobs:
  pysen-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ruff
        run: |
          ruff check *.py

      - name: Run Mypy
        run: |
          mypy *.py
